### ISSUE TITLE
Rendering transparency while back from another dimmension

### ISSUE THREAD

**Issue by panbanann** [DaFuqs/LootCrates#5] opened 2021-07-08 15:54 UTC
https://pastebin.com/7zL6kVS2
I had a common shulker crate next to the portal from another mod. When I teleported back to the overworld, the game crashed with this crash report.

**Comment by DaFuqs** [comment] 2021-07-09 07:34
What mod was it? I could not reproduce it with vanillas portals / the tp command.
Or was it multiplayer?

**Comment by DaFuqs** [comment] 2021-07-15 19:06
Fixed via https://github.com/DaFuqs/LootCrates/commit/c195349b53a6f676f0e0737b372cba40414a87be

**Closed by DaFuqs** 2021-07-15 19:06 UTC
Labels: bug
