### ISSUE TITLE
[BUG] Title player placed chests turn into loot crates.

### ISSUE THREAD

**Issue by TheRanker** [DaFuqs/LootCrates#32] opened 2022-04-05 20:38 UTC
**Describe the bug**
when you place down a normal oak chest.... it turns into a loot crate chest.
when you open a loot create and close it,, it then locked and n eeds key to open again.

**To Reproduce**
use version ModularLootcrates-3.0.0-1.18.2.jar

**Expected behavior**
player placed crafted chests should not turn into loot crates.
player instanced opened chests should not lock after closing the lootcrate.

**Screenshots**
https://cdn.discordapp.com/attachments/821206160660627516/960999225125109860/unknown.png
https://cdn.discordapp.com/attachments/821206160660627516/960993073213628456/unknown.png

**Comment by ChuckFaulker** [comment] 2022-04-05 21:02
Placed barrels and shulker boxes also turn into common loot crate versions

**Comment by DaFuqs** [comment] 2022-04-06 13:19
Fixed the locking ✔
I could not reproduce your chests turning into loot crates when placed by players issue, though. Can you paste the NBT of one such crate, please?

**Comment by DaFuqs** [comment] 2022-04-06 13:34
oh, I think I got it, nvm :)

**Comment by DaFuqs** [comment] 2022-04-06 13:36
fixed.

**Comment by Mattabase** [comment] 2022-10-22 09:51
3.4.0 Fabric - though using Quilt

Player placed chests are still being replaced when placed 

will grab my logs when I have the chance, just wanted to get this made while I had a moment of time

**Comment by DaFuqs** [comment] 2022-10-23 19:49
Does this happen immediately, or only after saving + quitting?

**Comment by DaFuqs** [comment] 2022-10-26 05:41
Fixed in 3.4.1, in combination with more performance inprovements

**Closed as completed by DaFuqs** 2022-10-26 05:41 UTC
Labels: bug
